apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nlp-show
  name: nlp-show
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nlp-show
      release: nlp-show-chart
  template:
    metadata:
      labels:
        app: nlp-show
        release: nlp-show-chart
    spec:
      containers:
        - env:
          image: medical-care-registry.cn-hangzhou.cr.aliyuncs.com/medical-care-public/nlp_show:v1.0.1
          imagePullPolicy: Always
          name: nlp-show
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: aliyuncs
